Validate new strategy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,7 +47,7 @@ on:
         description: "App secret eligible to create token to trigger dispatches"
 
 jobs:
-  deploy:
+  request:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -63,14 +63,18 @@ jobs:
           APP_ID: ${{ secrets.MANUAL_APPROVE_REQUESTOR_ID }}
           APP_PRIVATE_KEY: ${{ secrets.MANUAL_APPROVE_REQUESTOR_SECRET }}
 
+  deploy:
+    runs-on: ubuntu-latest
+    steps:
       - name: Add server public key
+        # if: ${{ inputs.manual == false || (inputs.manual && steps.request-approval.outcome != 'failure') }}
         id: add_keys
-        if: ${{ inputs.manual == false || (inputs.manual && steps.request-approval.outcome != 'failure') }}
         uses: ./.github/actions/cloud-keys
         with:
           CLOUD_RSA_KEY: ${{ secrets.CLOUD_RSA_KEY }}
 
       - name: Inject compose file to server
+        # if: ${{ inputs.manual == false || (inputs.manual && steps.request-approval.outcome != 'failure') }}
         uses: ./.github/actions/cloud-scp
         with:
           local_path: ./api/docker-compose.yml
@@ -79,6 +83,7 @@ jobs:
           CLOUD_ADDRESS: ${{ secrets.CLOUD_ADDRESS }}
 
       - name: Prepare database and inject variables
+        # if: ${{ inputs.manual == false || (inputs.manual && steps.request-approval.outcome != 'failure') }}
         run: |
           ssh -t -o StrictHostKeyChecking=no -i "${{ inputs.key_file }}" ${{ secrets.CLOUD_USER }}@${{ secrets.CLOUD_ADDRESS }} << EOF
             sudo -i
@@ -97,6 +102,7 @@ jobs:
           EOF
 
       - name: Remove previous service version
+        # if: ${{ inputs.manual == false || (inputs.manual && steps.request-approval.outcome != 'failure') }}
         uses: ./.github/actions/docker-stop-rm
         with:
           CLOUD_USER: ${{ secrets.CLOUD_USER }}
@@ -104,6 +110,7 @@ jobs:
           CONTAINER_NAME: ${{ inputs.CONTAINER_NAME }}
 
       - name: Deploy
+        # if: ${{ inputs.manual == false || (inputs.manual && steps.request-approval.outcome != 'failure') }}
         run: |
           ssh -t -o StrictHostKeyChecking=no -i "${{ inputs.key_file }}" ${{ secrets.CLOUD_USER }}@${{ secrets.CLOUD_ADDRESS }} << EOF
             sudo -i
