Added debug logs

diff --git a/.github/workflows/validation.yml b/.github/workflows/validation.yml
--- a/.github/workflows/validation.yml
+++ b/.github/workflows/validation.yml
@@ -119,12 +119,19 @@ jobs:
             if [[ "$deploy_job_status" == "success" ]]; then
               echo -e "\033[32mTrigger dispatch\033[0m"
               api_call=$(curl -X POST \
-                          -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
+                          -H "Authorization: token ${{ steps.generate_token.outputs.token }}" \
                           -H "Accept: application/vnd.github+json" \
-                          https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.run_id }}/dispatches \
-                          -d '{"ref":"release", "inputs":{"task":"deployed"}}')
+                          -d '{"ref":"release", "inputs":{"status":"deployed"}}') \
+                          https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.run_id }}/dispatches
               echo -e "\033[33m$api_call\033[0m"
-              exit 0
+
+              api_call_status=$(echo "$api_call" | jq -r '.status')
+              if [[ "$api_call_status" = "204" ]]; then
+                exit 0
+              fi
+              echo -e "\033[33mError $api_call_status calling dispatch.\033[0m"
+              echo -e "\033[33m$api_call\033[0m"
+              exit 1
             fi
 
             sleep 10
